# Generated by Django 5.1.15 on 2026-09-09 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='accepted_answers',
            field=models.TextField(blank=True, default='', help_text='For Short Answer questions: list accepted answers, one per line.'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Single Choice'), ('multiple', 'Multiple Choice'), ('true_false', 'True / False'), ('short_answer', 'Short Answer'), ('paragraph', 'Paragraph')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='Mark True if this is a correct answer'),
        ),
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_response', models.TextField(blank=True, default='')),
                ('is_correct', models.BooleanField(blank=True, help_text='Null for ungraded/paragraph questions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quizzes.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='quizzes.question')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='responses', to='quizzes.choice')),
            ],
            options={
                'ordering': ['question__order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_question_response')],
            },
        ),
    ]
