# Generated by Django 5.1.15 on 2026-09-29 09:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_question_accepted_answers_question_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='version_group',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
