# Generated by Django 5.1.15 on 2026-09-29 10:12

from django.db import migrations
import uuid

def generate_unique_uuids(apps, schema_editor):
    Question = apps.get_model('quizzes', 'Question')
    for question in Question.objects.all():
        question.version_group = uuid.uuid4()
        question.save(update_fields=['version_group'])

def noop(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_question_is_active_question_version_group'),
    ]

    operations = [
        migrations.RunPython(generate_unique_uuids, reverse_code=noop),
    ]
