# Generated by Django 5.1.15 on 2026-09-15 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(help_text='Primary key of the protected object.')),
                ('is_allowed', models.BooleanField(default=True, help_text='True → allow, False → explicit deny.')),
                ('content_type', models.ForeignKey(help_text='Content type of the protected object.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('learner', models.ForeignKey(help_text='Learner to which this rule applies.', on_delete=django.db.models.deletion.CASCADE, related_name='access_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['learner', 'content_type', 'object_id'], name='access_lear_learner_1fe8af_idx')],
                'unique_together': {('learner', 'content_type', 'object_id')},
            },
        ),
    ]
