# Generated by Django 5.1.7 on 2026-09-05 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_passing_score', models.PositiveIntegerField(default=75, help_text='Default passing score percentage across all quizzes (0-100)')),
                ('default_required_question_count', models.PositiveIntegerField(default=5, help_text='Default minimum questions required for a topic quiz to be marked assessment-ready')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.CharField(help_text='Short summary explaining what the learner will learn (2-4 lines max)', max_length=400)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('passing_score_override', models.PositiveIntegerField(blank=True, help_text='Optional passing score percentage override for this specific topic', null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content.subject')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF Document'), ('ppt', 'PowerPoint Presentation'), ('excel', 'Excel Practice File'), ('word', 'Word Document'), ('image', 'Image'), ('practice_file', 'Practice File'), ('external_link', 'External Link'), ('onedrive', 'OneDrive Link'), ('other', 'Other')], default='pdf', max_length=50)),
                ('url', models.URLField(help_text='Resource URL (e.g. OneDrive share link, PDF link, etc.)')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='content.topic')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(help_text='Video URL (e.g. OneDrive share link or direct video link)')),
                ('description', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, help_text='Optional duration string (e.g. 18:42)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='content.topic')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
