# Generated by Django 5.1.15 on 2026-09-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_resource_order_alter_subject_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='passing_score_override',
            field=models.PositiveIntegerField(blank=True, help_text='Optional passing score percentage override for all topics in this subject', null=True),
        ),
    ]
