# Generated by Django 5.1.15 on 2026-09-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_subject_passing_score_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='assessment_required',
            field=models.BooleanField(default=True, help_text='Whether learners must complete an assessment to complete this topic.'),
        ),
    ]
